CREATE TABLE  "T_TEST" (TEST_ID INT AUTO_INCREMENT PRIMARY KEY, TEST_NAME VARCHAR(45));
INSERT INTO  "T_TEST"  (TEST_NAME) VALUES ('flyway');
INSERT INTO  "T_TEST"  (TEST_NAME) VALUES ('flyway2');
INSERT INTO  "T_TEST"  (TEST_NAME) VALUES ('flyway3');